feat: add support for lambda to create a MosaicJSON representaion of a STAC API Search result
NASA-IMPACT/dashboard-api-starter pull request #8
Opened 2021-05-24 20:06 UTC by philvarner

Issue: https://github.com/MAAP-Project/ZenHub/issues/339

2021-05-25 15:08 UTC, abarciauskas-bgse commented on mosaic_api/README.md
> +An API to proxy STAC API searches into a MosaicJSON endpoint.
We might want to enumerate the endpoints we are creating (e.g. POST and GET mosaicjson) to make it clear we're not run a dynamic tiler for mosaicjson (yet!)

2021-05-25 15:12 UTC, abarciauskas-bgse commented on mosaic_api/README.md
> +## Contribution & Development
I think here and below can be removed? Or at least needs to be tailored for deploying the mosaic API, for example I don't think there is an install.sh script for this stack and it only deploys 2 stacks

2021-05-25 15:13 UTC, abarciauskas-bgse commented on mosaic_api/mosaic_api/api/api_v1/endpoints/mosaics.py
> +    "/mosaics/{mosaic_id}",
Naming convention changes requested: I think the API endpoint should be /mosaicjson and `mosaic_id` should be `layer` - this is consistent with https://api.cogeo.xyz/docs#/MosaicJSON

2021-05-25 15:14 UTC, abarciauskas-bgse commented on mosaic_api/mosaic_api/api/api_v1/endpoints/mosaics.py
> +
Just a style thing but should we have all these blank lines?

2021-05-25 15:21 UTC, abarciauskas-bgse requested changes
This is looks great so far @philvarner - I'm also hoping we can get a review from @vincentsarago so tagging him to take a look since he is the mosaicjson spec author.

So does the CDK deployment code work?

2021-05-25 15:23 UTC, vincentsarago commented
@philvarner 😭 we just updated a rio-tiler and cogeo-mosaic last week, I'm sorry for the trouble. I'll have a look at the PR as soon as I can!

2021-05-25 15:25 UTC, vincentsarago commented on mosaic_api/mosaic_api/api/api_v1/endpoints/mosaics.py
> +import aiohttp
❤️

2021-05-25 15:26 UTC, vincentsarago commented on mosaic_api/mosaic_api/__init__.py
> +version = pkg_resources.get_distribution(__package__).version
we should avoid this, it makes startup really slow. 

We switched to hardcoded version in most of out lib (and use https://github.com/c4urself/bump2version to update versions accros the files)

2021-05-25 15:27 UTC, vincentsarago commented on mosaic_api/mosaic_api/api/api_v1/endpoints/mosaics.py
> +from mosaic_api.core.config import MOSAIC_API_ROOT
I would suggest to use iSort to sort the module imports, but this is not mandatory

2021-05-25 15:33 UTC, vincentsarago commented on mosaic_api/mosaic_api/api/api_v1/endpoints/mosaics.py
> +        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="invalid mosaic ID")
you can make path parameter required using `fastapi.Path(...)`  and also add description. As we do in https://github.com/developmentseed/titiler/blob/master/titiler/core/titiler/core/factory.py#L297

2021-05-25 15:36 UTC, vincentsarago commented on mosaic_api/mosaic_api/api/api_v1/endpoints/mosaics.py
> +        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="invalid mosaic ID")
you can also mix path/query definition using `Dependencies` 

e.g: this is the dependency we use in api.cogeo.xyz.

```python
@dataclass
class MosaicParams:
    """Create mosaic path from args"""

    layer: str = Query(..., description="Mosaic Layer name ('{username}.{layer}')")

    def __post_init__(self,):
        """Define mosaic URL."""
        pattern = (
            r"^(?P<username>[a-zA-Z0-9-_]{1,32})\.(?P<layername>[a-zA-Z0-9-_]{1,32})$"
        )
        match = re.match(pattern, self.layer)
        if not match:
            raise HTTPException(
                status_code=400, detail=f"Invalid layer name: `{self.layer}`",
            )

        meta = match.groupdict()
        self.username = meta["username"]
        self.layername = meta["layername"]
        if mosaic_config.backend == "dynamodb://":
            self.url = f"{mosaic_config.backend}{mosaic_config.host}:{self.layer}"
        else:
            self.url = f"{mosaic_config.backend}{mosaic_config.host}/{self.username}/{self.layername}{mosaic_config.format}"
```

2021-06-14 19:57 UTC, abarciauskas-bgse commented
I think we can close this in favor of using https://github.com/NASA-IMPACT/titiler/ for mosaic management and tiling right @philvarner ?

2021-06-15 13:25 UTC, closed without merging